---
title: "Circle"
author: "Ziwei Tian (ZIWEIT)"
date: "2022-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mlr3)
generator = tgen("circle")
task = generator$generate(3000)
data_circle = task$data()
data_circle$y = ifelse(data_circle$y == 'A', 0, 1)

test_id = sample(1:3000, 600)
train_circle = data_circle[-test_id, ]
train_circle_x = as.matrix(train_circle[, -1])
train_circle_y = train_circle$y
test_circle = data_circle[test_id, ]
test_circle_x = as.matrix(test_circle[, -1])
test_circle_y = test_circle$y
```

```{r}
plot(test_circle$x1, test_circle$x2, col = as.factor(test_circle_y))
```


### Linear kernel

```{r}
linear_circle = KLR(train_circle_x, train_circle_y, kernel = "polynomial", d = 1)

prob_train_circle = predict.KLR(linear_circle)
pred_train_circle = ifelse(prob_train_circle <= 0.5, 0, 1)
prob_test_circle =  predict.KLR(linear_circle, test_circle_x)
pred_test_circle = ifelse(prob_test_circle <= 0.5, 0, 1)

(train_err = mean(train_circle_y != pred_train_circle))
(test_err = mean(test_circle_y != pred_test_circle))

plot(test_circle$x1, test_circle$x2, col = as.factor(pred_test_circle))
```

### Polynomial kernel

```{r}
poly_circle = KLR(train_circle_x, train_circle_y, kernel = "polynomial", d = 3)

prob_train_circle = predict.KLR(poly_circle)
pred_train_circle = ifelse(prob_train_circle <= 0.5, 0, 1)
prob_test_circle =  predict.KLR(poly_circle, test_circle_x)
pred_test_circle = ifelse(prob_test_circle <= 0.5, 0, 1)

(train_err = mean(train_circle_y != pred_train_circle))
(test_err = mean(test_circle_y != pred_test_circle))

plot(test_circle$x1, test_circle$x2, col = as.factor(pred_test_circle))
```

### RBF

```{r}
RBF_circle = KLR(train_circle_x, train_circle_y, kernel = "RBF")

prob_train_circle = predict.KLR(RBF_circle)
pred_train_circle = ifelse(prob_train_circle <= 0.5, 0, 1)
prob_test_circle =  predict.KLR(RBF_circle, test_circle_x)
pred_test_circle = ifelse(prob_test_circle <= 0.5, 0, 1)

(train_err = mean(train_circle_y != pred_train_circle))
(test_err = mean(test_circle_y != pred_test_circle))

plot(test_circle$x1, test_circle$x2, col = as.factor(pred_test_circle))
```

### Laplace

```{r}
laplace_circle = KLR(train_circle_x, train_circle_y, kernel = "laplace")

prob_train_circle = predict.KLR(laplace_circle)
pred_train_circle = ifelse(prob_train_circle <= 0.5, 0, 1)
prob_test_circle =  predict.KLR(laplace_circle, test_circle_x)
pred_test_circle = ifelse(prob_test_circle <= 0.5, 0, 1)

(train_err = mean(train_circle_y != pred_train_circle))
(test_err = mean(test_circle_y != pred_test_circle))

plot(test_circle$x1, test_circle$x2, col = as.factor(pred_test_circle))
```

### Sigmoid

```{r}
sigmoid_circle = KLR(train_circle_x, train_circle_y, kernel = "sigmoid")

prob_train_circle = predict.KLR(sigmoid_circle)
pred_train_circle = ifelse(prob_train_circle <= 0.5, 0, 1)
prob_test_circle =  predict.KLR(sigmoid_circle, test_circle_x)
pred_test_circle = ifelse(prob_test_circle <= 0.5, 0, 1)

(train_err = mean(train_circle_y != pred_train_circle))
(test_err = mean(test_circle_y != pred_test_circle))

plot(test_circle$x1, test_circle$x2, col = as.factor(pred_test_circle))
```

```{r}
logit_circle <- glm(y ~ x1 + x2, data = train_circle, family = "binomial")

prob_train_circle = predict(logit_circle, train_circle, type = "response")
pred_train_circle = ifelse(prob_train_circle <= 0.5, 0, 1)
prob_test_circle = predict(logit_circle, test_circle)
pred_test_circle = ifelse(prob_test_circle <= 0.5, 0, 1)

(train_err = mean(train_circle_y != pred_train_circle))
(test_err = mean(test_circle_y != pred_test_circle))

plot(test_circle$x1, test_circle$x2, col = as.factor(pred_test_circle))
```

```{r}
prob_test_circle = calibrateBinary::KLR(train_circle_x, train_circle_y, test_circle_x, lambda = 0.001, kernel = "exponential", power = 1, rho = 1)
pred_test_circle = ifelse(prob_test_circle <= 0.5, 0, 1)

(test_err = mean(test_circle_y != pred_test_circle))

plot(test_circle$x1, test_circle$x2, col = as.factor(pred_test_circle))
```

```{r}
prob_test_circle = calibrateBinary::KLR(train_circle_x, train_circle_y, test_circle_x, lambda = 0.001, kernel = "matern")
pred_test_circle = ifelse(prob_test_circle <= 0.5, 0, 1)

(test_err = mean(test_circle_y != pred_test_circle))

plot(test_circle$x1, test_circle$x2, col = as.factor(pred_test_circle))
```

